# Generated by Django 3.1.4 on 2020-12-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='First_Name',
            field=models.CharField(choices=[('drinks', 'drinks'), ('apetizers', 'apetizers'), ('treats', 'treates'), ('entrees', 'entrees')], max_length=60),
        ),
    ]
