# Generated by Django 3.1.4 on 2020-12-03 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20201202_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='Prefix',
            field=models.CharField(choices=[('Ms', 'Ms'), ('Mrs', 'Mrs'), ('Mr', 'Mr')], default='---------', max_length=60),
        ),
    ]
